### ISSUE TITLE
Public RSVP?

### ISSUE THREAD

**Issue by gearmonkey** [computeranonymous/computer#113]
So right after this https://twitter.com/whycomputer/status/385342997384425472 I had a friend of mine DM me saying he was coming but wasn't comfortable announcing that kind of thing in public. I'm not super concerned about the  slightly incorrect numbers on attendance, but it occurs to me that those who don't want to announce their attendance publicly may be discouraged from attending, as a result of interpreting requests for  attendance as a prerequisite for attending.

What are other people's thoughts?

**Comment by adacable** [comment]
@tef or @ntlk would you tweet to make it clear that announcing attendance is not compulsory?

I think it was a badly phrased tweet which shouldn't be a problem in future.

**Comment by jcoglan** [comment]
I know people for whom public disclosure of their location is a huge problem and would be put off by this, better to make it clear it's not required or they can RSVP privately.

**Comment by tef** [comment]
@ntlk sorted things out i think
