### ISSUE TITLE
Facebook pages?

### ISSUE THREAD

**Issue by adacable** [computeranonymous/computer#118]
At least part of computer is about getting people who don't often go to meetups to come to one. 
At the moment we have an IRC channel, a twitter, a github and a website. Most people know what two of these things are and spend 90% of their time in one place:facebook. 
We don't have a facebook page and I believe that this lack biases out audience towards more traditionally tech-engaged people. 

Arguments against a facebook page:
- A page would be a place for people to attack/harass computer/attendees.
- facebook is evil

**Comment by ntlk** [comment]
Facebook is evil, destroying the web (aka my life and job) and I am wholeheartedly against it.

I'd rather make it easier for people to participate in other ways (I have volunteered to make a good irc guide for newbies for example).

**Comment by adacable** [comment]
@ntlk I strongly agree with you(thankfully, it's also dying)

But we need to engage everyone, especially those who don't move in traditional tech circles.

Facebook is the place to do it, but our presence should be minimal (events for each meet) and encourage engagement elsewhere.

**Comment by ntlk** [comment]
That would be an acceptable compromise as long as we helped get people on IRC instead for chat and stuff

**Comment by johnd** [comment]
@ntlk FaceBook is definitely evil, but it's where the people who don't go to tech events spent their time online. At least one person going to the Edinburgh meetup is going because I mentioned it on FB and 'tagged' them.

I think we need a 'page' to allow people to like or share it, and events for each meeting. But again, I don't really know FaceBook that well so I'm not sure on the best way to handle that sort of thing.

**Comment by adacable** [comment]
#42 is relevent here. Facebook should funnel people to the site/IRC. The IRC needs a web interface.

**Comment by tef** [comment]
https://www.facebook.com/ComputerAnonymous

**Comment by tef** [comment]
- Comments Turned off.
- No-one else can post to that page.

**Comment by adacable** [comment]
Closing. Maybe a point on the organizers page?
