### ISSUE TITLE
East london feedback for first meet up 

### ISSUE THREAD

**Issue by tef** [computeranonymous/computer#121]
We still have a lot to learn.

when should we next meet 
where should we consider meeting next
were there any problems or issues, be it behaviour, accessibility or things I'm forgetting

**Comment by adacable** [comment]
As on twitter, feel free to contact me if you need someone to talk to in confidence about anything at the meetup, drop me a line and I'll sort it. 

email:drcable@tarbwf.com (GPG key on servers if nsa-afraid)
twitter:drcabl3
freenode:drcable (query or mention)
tumblr:drcabl3 (anon asks on, if you don't want to leave a name)

I'm queer, not-cis, and not male, but otherwise privileged, however try my best to be an ally to most causes. While I have stated opinions on otherkin issues I'm still forming an opinion and will try to act as a good ally for the time being, and in all computer related matters.

**Comment by DRMacIver** [comment]
So my main feedback is that I thought it was great and everyone else I talked to seemed to think the same. Not ruling out the possibility of having missed something unfortunate, but so far so good.

I think the main issues I spotted were:
- The transport links were not as accessible as we'd have liked. I'm not sure what the exact state was, but it seemed to be not amazing. The pub was fine (I think?) for accessibility, but it turns out people have to actually get there.
- Wow what a crowd. I wonder if there's a way to have smaller computer meetups too for people who find crowds intimidating?
- The acoustics were such that with the aforementioned crowd it was really very loud indeed. 
- It was a very white group. I don't get the impression (but privilege, so I probably wouldn't) that this was a problem for the people who were there and not white, but it's a sign that we need to do some outreach.

**Comment by qntm** [comment]
Seems like two of these issues are diametrically opposed to one another. If the next meet is more accessible, even more people might turn up, which is kind of mind-boggling

**Comment by janepipistrelle** [comment]
Agree with the above. As someone with hearing issues, I found it hard at times. But that is normal for me in pubs or even groups where several conversations are happening simultaneously. 

I'm gonna be selfush & and ask if next friday would work? I'm in London that day. No worries if not, I'm sure I can still get people to pub, right? :wink:

Regarding outreach, I hope being seen to be inclusive works to make folk want to come along.  Personally I'm not comfortable with being targetted (eg with women-only groups) as it makes me feel like people are traating me differently because I'm part of a certain group. But totally open to suggestions of how to do outreach in ways that welcome people.

**Comment by DRMacIver** [comment]
I generally think the right way to do outreach is basically do our best to have a code of conduct that makes it clear we're aware of specific issues people are likely to face and will handle them well (e.g. we seem to be doing quite well for gender related issues) and making sure a diverse group of people know about it. My guess is that we've just not done enough of either of these on racial issues, but I don't see any impediment to us doing so.

**Comment by adacable** [comment]
@DRMacIver I think that outreach also involves going to non-computer spaces and talking about computer. like facebook, but also like uni depts/etc.

**Comment by russss** [comment]
Don't discount the first-meeting syndrome; I think a lot of people will have made a greater effort than normal to attend this one, and so I'd wait for a few to happen before making any decisions.

Additionally, controlling the frequency of meetings is probably the best way of controlling their size. I very much doubt we'll see 40 people turning up on a weekly basis.

**Comment by adacable** [comment]
@russss I was talking about this. There's a possibility this could get /bigger/ with nervous people waiting to see if it was safe, and word spreading further.

**Comment by tef** [comment]
My general thoughts
- The venue was good in that we could fit inside it, and I have had no issues raised about the people, food, or beer in the pub, and they'd like us back.
- We should run another Computer, in the Pembury on the first thursday of next month. 
- If we run another computer each month, we should pick a venue around Waterloo/London Bridge, as it's easier to get to from the south of london. I think @squirmelia was interested in running this.
- People liked the novelty of the algorithm @DRMacIver proposed, and seemed interested in having a somewhat floating weekly meetup, on a different day of the week each time.
- Someone told me that they liked that it wasn't a networking meetup, and enjoyed not having to bring their day job to the meeting.

**Comment by qntm** [comment]
One data point makes poor statistics, as they say

**Comment by adacable** [comment]
@ferno If you repeat an experiment with the same conditions(as we're planning) then you will almost certainly get the same outcome.

**Comment by tef** [comment]
@ferno This is why we want to run another.  :-)

**Comment by russss** [comment]
I agree with the idea of the next major meetup being at the opposite end of London at the opposite end of the month. I also like the idea of having consistent locations for events at consistent times of the month.

Unfortunately my knowledge of pubs (as indicated by http://goodpubs.org) is a bit spotty once you move away from northeast London. My only immediate suggestion is http://www.caskpubandkitchen.com/ which is near Victoria, however I can't remember how accessible it is.

**Comment by tef** [comment]
In which case i'm going to take a tinpot dictator decsion and fix the east london group to the first thursday of the month at the pembury

And try and get the other london group to pick a day and venue around the third week of the month.

**Comment by ntlk** [comment]
:+1:

On 4 October 2013 at 13:35:30, tef (notifications@github.com) wrote:

In which case i'm going to take a tinpot dictator decsion and fix the east london group to the first thursday of the month at the pembury

And try and get the other london group to pick a day and venue around the third week of the month.

**Comment by janepipistrelle** [comment]
:+1: 

—

**Comment by tef** [comment]
I tried to make a PR, but i failed. So it's a commit now.

**Comment by ntlk** [comment]
My main gripe was that people don't have their twitter/freenode handles floating above their heads, or at the very least twitter avatars, so I probably missed out on introducing myself to people I already know. We should have friggin name badges next time maybe?

**Comment by tef** [comment]
Oh god name badges. Noooooooooooo

Party hats i could get behind

**Comment by ntlk** [comment]
Party hats with twitter handles on

**Comment by didlix** [comment]
Let's do the meetup in second life.

**Comment by gearmonkey** [comment]
:+1: same issue. I'm a fan of name badges, even if they look a bit rediculous...

**Comment by ntlk** [comment]
At some event at Mozilla they had cool name stickers: instead of the "HELLO my name is" there were different ones, like "HELLO my favourite terminal command is", so that could maybe also help break the ice

**Comment by ntlk** [comment]
Sorry, closed by accident, computer :-(

**Comment by didlix** [comment]
I could look into doing a north london meetup.

**Comment by adacable** [comment]
Request for name badges/or whatever: Pronoun(or gender) field. Only effects a small %age of us but it never hurts cis people to explicitly say what gender they are/etc.

**Comment by drtortoise** [comment]
I would like to opt out of having to wear a badge that says my gender

**Comment by tef** [comment]
there are people who are not out. there are many who are uncomfortable with namebadges. I'm not in favour of wearing identification or requiring personal information to be in display in a public place

**Comment by tef** [comment]
namebadges are a strong, strong -1 from me, as we're not in a private space

**Comment by drtortoise** [comment]
"it never hurts cis people to explicitly say what gender they are/etc."

maybe I don't like being labelled

**Comment by janepipistrelle** [comment]
I also think namebadges should be optional or not at all (also don't like being labelled).

**Comment by adacable** [comment]
@drtortoise Fair enough, though if you have the time/Spoons/health/etc (ATM I understand if you don't) I'd consider it a personal favour if you'd consider whether not having to examine and state your gender is a privilege, and whether this is a privileged reaction. No biggie if you choose not to, but it might be something to think about. 

Dislike of labelling is a fine attitude(and one which I hold to a certain extent)

I never intended it to be compulsory, or anything among those lines.

If people have issues with it that they believe override the advantages of trans\* comfort I accept those at face value and this is cool. 

@Tef also makes a good point about safety. 

Sorry If this suggestion caused any damage to anyone.

**Comment by tef** [comment]
I'm unsure if it's a cis thing to be uncomfortable having personal information displayed, and as mentioned, it's a lot to ask of someone who is uncomfortable with social environments. I'm unsure it would provide much trans\* comfort, as for some i've talked to it's a choice between writing the gender people assume, or outing themselves.

**Comment by tef** [comment]
having some optional badges provided will exert pressure on those who don't want to wear personal information in public. as i said, i am strongly against having an expectation to wear personal information in a public space.

to wit, safety isn't a good point, it's a fundamental issue. unless we can demonstrate that expecting or suggesting people wear personal information for the benefit of others doesn't in anyway compromise safety, i'm _incredibly_ against it.

edit: I'm not against people bringing their own name badges if they feel it helps them (i've met people who have an faq on a t-shirt), but I don't really want to set a precedent of personal information being openly displayed

**Comment by adacable** [comment]
@tef not a cis thing to be uncomfortable having information displayed. a cis thing to not have to constantly examine and explicitly state your own gender. 

As above. fine without name badges. Not going to argue more on this issue.

**Comment by AgentAntelope** [comment]
I'd just like to say that one of the issues I had with this while on crutches was not the accessibility of the venue (step free all the way from my desk, woo) but the accessibility of the conversations. A large majority of people decided to have standing-up conversations, which I simply wasn't capable of.

I'm not sure there's a solution to this, and I certainly can't think of an easy one, but I thought I'd mention it.

**Comment by tef** [comment]
@AgentAntelope I'm open to new venues, but i am not expecting such a large turnout next month. I think we'll have to wait and see. I am also unaware of any good simple solutions to the problems of unexpected popularity.

**Comment by AgentAntelope** [comment]
@tef I was very happy with the venue actually :) I suspect when there's a crowd of people who know each other at least a bit more people will sit down :)

**Comment by tef** [comment]
Aside, and while i'm still in this issue, i'm going to have a little bit of a self indulgent whine:

I'm taking a break from computer this weekend because handling all the pull requests, issues, and conflicts of ideals is tiring, and I need to spend a few days not worrying about things.

I'm resisting the urge to fix some of the style issues in the code of conduct this weekend (it is not as informal or as friendly as I would like), and there are lots of conflicting demands made over what computer should be. I'm going to stick to my original plan. Computer is an informal  social group, not a safe space, nor a place for outreach, nor education.

I feel like it's been an uphill battle against explicit rules, behaviours, and i'm finding it real hard to cater to the morass of conflicting individual preferences. Frankly, if there is a conflict in ideals that is untenable, I'm going to be a tinpot dictator and say "Fork the repo, get your own name, and run your own meetup".

I'm also open for someone else organising their own meetup in a different venue, as  Ultimately it may turn out that computer doesn't please everyone (we can't) or that other people feel they can do better (they can!). I welcome other people to take up the challenge.

**Comment by tef** [comment]
(This isn't a dropping of the mic, nor asking people to apologise (that's silly), but a little reminder that I am a burnt up meat sack, and so I'm not going to be around this weekend to help)

**Comment by joliss** [comment]
Sounds good @tef. Go be benevolent dictator.

As for feedback, I enjoyed the meetup. Great format.

If we did a weekly thing, I'd probably go sometimes but not every week. That's not a bad thing. If many people attend sporadically, it means there's a smaller and ever-changing group of people. That seems good.

As for the place, wouldn't mind varying across London. I'd happily sit on the tube for an hour.

Grabbing people's twitter handles from Doodle was useful. It helps for staying in touch, and remembering people's names. Maybe have an optional signup list where people can post their handles, if they want to be found online? (meetup.com, Doodle, a wiki page, or whatever.)

**Comment by ntlk** [comment]
@joliss I agree it would be good to have a place where people who want to can identify themselves, so we can find one another online afterwards. I'm gonna have think about the simplest way to do this so people can add/remove their own names

**Comment by didlix** [comment]
Dislike name badges and gender/sex/pronoun fields. Inclusive shouldn't be about wearing a badge of labels.

In a pub environment it would likely draw unwanted attention from people not attending computer who don't participate in our code of conduct.

**Comment by ntlk** [comment]
@didlix yeah, privately lots of people said the same thing to me, especially the point about attention from others in a public space.

**Comment by tef** [comment]
I'm a fascist: No namebadges. The revolution will not be namebadged. 

Official Computering Policy has been decided.

**Comment by didlix** [comment]
@ntlk @tef :+1:

**Comment by ntlk** [comment]
Okay can I close this now? If anyone else has any comments they can still add them here or speak to anyone involved on IRC.

**Comment by ntlk** [comment]
Actually, I'm not asking, I'm just closing :)

**Comment by didlix** [comment]
Can we have a summary of the action points, and then close it?

**Comment by ntlk** [comment]
We agreed that need to look for accessible venues for meetups across London, and it would be good to have them in different places so people don't have to travel far, but the first Thursday of the month at Pembury Tavern is now a thing.

There are no action points as far as I can see.

**Comment by tef** [comment]
- Find a willing chump to run another meetup outside of hackney, on a different day of the week, in a different week of the month. 
- Stick to the pembury on the first thursday for now.
- I'm going to clean up index.html to make what computer is _clear_, because i'm exhausted from pushing back the requests for more rules, more formalism, or worse, randomised algorithms to solve social problems :-)

**Comment by didlix** [comment]
I am chumpy enough to give a North London one ago.
