### ISSUE TITLE
"Etiquette" section

### ISSUE THREAD

**Issue by DRMacIver** [computeranonymous/computer#122]
It might be worth having a section of etiquette guidelines: Things which we're not really going to punish/exclude you for not adhering to, but we might think you're a bit of a dick.

The thing that made me think of this is that I noticed last night that several peoples' preferred form of address doesn't match what you'd expect from their online presence - e.g. some people prefer to go by their handle even offline, some people prefer to be referred to by their last name, etc. It would be worth having a norm of always asking what peoples' preferred form of reference is even if you recognise their name from online. (Note: Repeatedly calling someone by the wrong name, especially when it misgenders them, is a more serious problem. This is more about asking first so you don't innocently get it wrong)

I'm happy to draft such a section if people think it's a good idea, but I don't have any other entries for it which would make it look a bit barren. Thoughts/suggestions?

**Comment by adacable** [comment]
Yes please. me and @janepipistrelle were having a chat about gender and stuff and I asked a dude if he was a dude and he seemed a bit put out. Not an issue, really, but something that an etiquette guide might fix.

**Comment by tef** [comment]
I'm unsure if more text is the solution to this.

**Comment by adacable** [comment]
This is a good point. We'd need a lot of text. and that is against what is pretty much a founding principal(and a good one).

**Comment by ntlk** [comment]
I'm not sure we need guidance on that. People ask one another whet their name is when they introduce themselves and some people will give their handle / name / etc, and that's what you're going to call them, right? I personally find it annoying when I introduce myself by my handle to people who I think might know me from the internet and they keep asking about my actual name, but I don't think it's something that needs to be covered by computer. 

On 4 October 2013 at 08:57:49, David R. MacIver (notifications@github.com) wrote:

It might be worth having a section of etiquette guidelines: Things which we're not really going to punish/exclude you for not adhering to, but we might think you're a bit of a dick.

The thing that made me think of this is that I noticed last night that several peoples' preferred form of address doesn't match what you'd expect from their online presence - e.g. some people prefer to go by their handle even offline, some people prefer to be referred to by their last name, etc. It would be worth having a norm of always asking what peoples' preferred form of reference is even if you recognise their name from online.

I'm happy to draft such a section if people think it's a good idea, but I don't have any other entries for it which would make it look a bit barren. Thoughts/suggestions?

**Comment by tef** [comment]
Note: If we can rewrite "Don't assume a person's gender, their preferred pronouns, sexuality, abilities or anything else personal. If in doubt ask respectfully." to be a little clearer about identity, then i'm happy to include a change.

If we want to add another sentence, I'm pretty much dead set against it, unless I can be convinced that it is necessary

**Comment by adacable** [comment]
@tef :+1:

**Comment by tef** [comment]
Open a PR if you think you can improve this, but I am unsure that adding more text will solve the problem.
