### ISSUE TITLE
East london: The noise issue has not gone away. 

### ISSUE THREAD

**Issue by adacable** [computeranonymous/computer#130]
Even if 50% of the people turn up to the next computer, or if we increase meeting frequency by 4 and we only get a 50% turn out(some people want to computer a lot. It is often the only safeish space to talk about tech) then the noise will probably be too loud for a lot, and the crowding problem will still be there. 

If we think #123 isn't a good Idea, then we need to think about the venue &c to make this better. 

This issue should be closed when we have measures in place lower noise and crowding at the next meeting. Until then we have a significant issue and it should remain obvious. 

Ideas?

**Comment by tef** [comment]
I am unsure why this is a seperate bug after the closing of David's proposal. If this is feedback for the last meeting, we have a bug there.

**Comment by tef** [comment]
But frankly, without massively changing the organisation of the group, there is very little we can do about noise.

We'd have to ticket it to reduce numbers. This is time and effort intensive,  and we can't have tickets in a public venue (how do we check tickets?). So we'd need a private venue (and the Pembury is actually one of the biggest venues we could find for 0 cost)/

And as I mentioned in the proposal, people are welcome to go and run their own meetups of a different nature (for ex: speed dating), but I am reluctant to change what we have or increase the burdern of organising meetups.

**Comment by adacable** [comment]
It's a separate bug because it's a problem which we haven't solved. 

If we can't solve it then we still need to see it as a problem("an issue"), albeit one we haven't solved.

It's a specific problem, and one which we need to think about solving. Not a general point on feedback. 

If the pembury is our only venue option, what can we do to make it quieter or get some quieter space for people who can't deal with huge groups?

**Comment by tef** [comment]
It's more than a general problem, it is literally a consequence of numbers of people, not venues. The only way to deal with noise is simply to have less people in a room. Unless someone has a better idea.

As DRM pointed out, the only way to have less people in a meetup is not to invite people, or have seperate or smaller meetups.  As I said when I closed it, I'm welcome other people to run their own meetups, but I feel ticketing or rate limiting attendance, or charging for admission would change the nature of what this meetup was for.

I am happy for the people who want to run smaller meetups to do so, but as said I believe it to be non-canon.

**Comment by ntlk** [comment]
If there are any practical means to reduce noise maybe we can open separate issues on those? Currently what we can do is limited as any venue will become noisy if the meetup continues being popular. Pembury is generally not as noisy as many other pubs, and there is no music, so I struggle to think of ways to make it better, hence closing this until some ideas are proposed.
