### ISSUE TITLE
Computer in other londons.

### ISSUE THREAD

**Issue by tef** [computeranonymous/computer#132]
- North London
- Southwest/Central London

**Comment by tef** [comment]
@didlix has volunteered to run a north london

@squirmelia is looking at venues for Southwest/Central london

**Comment by ntlk** [comment]
@didlix wanna create a North London page?

**Comment by didlix** [comment]
@ntlk I'm going to, just been a bit busy with School & Work.

**Comment by tef** [comment]
We have four londons. Closing
