### ISSUE TITLE
Computer in German

### ISSUE THREAD

**Issue by tef** [computeranonymous/computer#137]
- [x] Update translation to match current index.html
- [x] Make seperate index.html, and woo ~internationalisation~
- [x] Update berlin/hamburg pages to match group page style
- [x] Proof read

**Comment by greelgorke** [comment]
if noone take this till next week, i probably could find few ours. i'd like to be added as contributor to this repo :)

**Comment by tef** [comment]
The problems are as follows:

The german text no longer matches the english text. The Berlin and Hamburg meetings don't have meeting pages, but the home page with the meeting tacked onto the end.

What I'm imagining is that we do the following:

Create an index.de.html, which contains /just/ the german version of index.html 
Index.html and Index.de.html both link to each other
the meeting pages for berlin and hamburg, i.e remain bilingual, but without all of the introductory text, with links back to index.html and index.de.html, and looking a lot more like the other meeting pages

Does this seem sensible?

**Comment by greelgorke** [comment]
yes. i'm on it now

**Comment by greelgorke** [comment]
@tef where should i place the link to the corresponding index.html?

**Comment by tef** [comment]
Looks Good. 

Does anyone want to proof read ?

**Comment by tef** [comment]
Ok, it seems to be written in german.

**Comment by urschrei** [comment]
Typos at
- https://github.com/greelgorke/computer/commit/9783f6e983ee849e3ae3a528304f7793e78b2247#diff-0c09b4defbb40230c12a533372e8fb59R16
- https://github.com/computeranonymous/computer/compare/53e7e9233c80...2e270b3b2d50#diff-6c0d2be4f8479a7ec2d7014a14447599R16

should be "verstehst".

https://github.com/computeranonymous/computer/compare/53e7e9233c80...2e270b3b2d50#diff-6c0d2be4f8479a7ec2d7014a14447599R16 – this should be "group's", not "groups".

https://github.com/computeranonymous/computer/compare/53e7e9233c80...2e270b3b2d50#diff-bd0ede99972a84d388ef87900a972bc5R20 – this should be "Cocktails"

https://github.com/computeranonymous/computer/compare/53e7e9233c80...2e270b3b2d50#diff-bd0ede99972a84d388ef87900a972bc5R20 –  "zu reden willst" should be "reden willst"

https://github.com/computeranonymous/computer/compare/53e7e9233c80...2e270b3b2d50#diff-bd0ede99972a84d388ef87900a972bc5R28 "am ende des tages" should be "letztendlich"

https://github.com/computeranonymous/computer/compare/53e7e9233c80...2e270b3b2d50#diff-bd0ede99972a84d388ef87900a972bc5R28 – remove extra "beteiligen" at the end of this sentence.

https://github.com/computeranonymous/computer/compare/53e7e9233c80...2e270b3b2d50#diff-bd0ede99972a84d388ef87900a972bc5R49 – typo, should be `Bel&auml;stigung`

https://github.com/computeranonymous/computer/compare/53e7e9233c80...2e270b3b2d50#diff-bd0ede99972a84d388ef87900a972bc5R51 – typo, should be "Alkohol"

https://github.com/computeranonymous/computer/compare/53e7e9233c80...2e270b3b2d50#diff-bd0ede99972a84d388ef87900a972bc5R55 – typo, should be "konkrete"

**Comment by greelgorke** [comment]
@urschrei looks like you solved them yourself, nice :)

i'm preparing another pr

**Comment by tef** [comment]
Looks like the problem is mostly solved. Closing the issue, more fixes welcome!
