### ISSUE TITLE
Computer in Cardiff?

### ISSUE THREAD

**Issue by sgsabbage** [computeranonymous/computer#140]
I'd love to get a branch of Computer going in Cardiff. Any advice on doing so would be gratefully received.

Also, is there a noun for an instance of Computer, or is 'group' correct?

**Comment by omgmog** [comment]
The way we did it in Oxford is:
- Just make a page (fork this repository, add your uk_cardiff.html, add your page to the index.html, make a pull request to get your page on http://computeranonymous.org/)
- Talk to folks on IRC to see if anybody is interested
- Talk to folks on Twitter to see if anybody is interested
- Get local groups to retweet about it
- Mention it on local newsgroups
- Pick a venue
- Do it.

It went from me going "that sounds cool we should do one in Oxford" one week ago to us having our meeting last night with a turnout of 12 people.

**Comment by janepipistrelle** [comment]
Hah, I was just writing exactly that. _deletes_.

**Comment by igalic** [comment]
whoo! Now I need to do this for Vienna.

**Comment by ntlk** [comment]
What @omgmog wrote should probably go in the how-to-make-your-own-meetup guide, but I'm closing this for now since Cardiff has own page
