### ISSUE TITLE
Do some multi-disciplinary outreach

### ISSUE THREAD

**Issue by ntlk** [computeranonymous/computer#17]
People across all disciplines are interesting, and also need computer support, so let's invite designers, artists, scientists, etc. If you know any cool people outside of the tech bubble you should ask them to come along

**Comment by janepipistrelle** [comment]
YES.

As a biologist this is relevant to my interests.

**Comment by ntlk** [comment]
@janepipistrelle will you invite some friends across disciplines then please? :D

**Comment by gearmonkey** [comment]
I have pushed to some yet-to-leave academics Computer Science types, will also try to get some hardware folk aware of things...

**Comment by janepipistrelle** [comment]
@ntlk sure. everyone should.

**Comment by ntlk** [comment]
This can be closed now, I think we all want to meet with interesting people so it's on individuals to invite them.
