### ISSUE TITLE
RSVPs for NYC on October 29 

### ISSUE THREAD

**Issue by anarchivist** [computeranonymous/computer#185]
Hi, if you're going to be attending the first [NYC meetup](http://computeranonymous.com/us_newyork.html) on 29 October 2013, and if you are comfortable announcing your attendance, please comment here or issue a pull request adding your name to the section of the page listing attendees.

If you are interested in attending, would like to RSVP, and do not want to have your handle listed publicly on the page linked above, please indicate this clearly.

I can also be contacted via Twitter at **@anarchivist** and via [email](mailto:mark@matienzo.org).

**Comment by ModalUrsine** [comment]
I can't be there physically this time around, but I'm interested being kept posted  about what's happening.

**Comment by anarchivist** [comment]
@ModalUrsine duly noted!

Decent turnout; ~14 people!

**Comment by alexglow** [comment]
Hey NYC computer! I will be over there, starting tomorrow, for the weekend
:D
Friday I'll be at this conference: softwareandart.com/?page_id=1161
I will be doing this at 11:45pm on Saturday --> sleepnomorenyc.com
and I'd be hell of down for some hangouts at some point before I leave on
Sunday (time TBD)! Maybe a Citibike ride through some interesting places?
Particularly awesome if any of y'all frequent NYC Resistor, as I hope to
visit.

Also, anybody know of a decent hostel that wouldn't be terribly far from
the conference (*The New School http://newschool.edu/, 66 W. 12th Street,
NYC) *or Sleep No More (530 W. 27th St.)?

Thanks! Hope this isn't too much of an abuse of the network :o
- the_merlin

On Wed, Oct 30, 2013 at 4:32 AM, Mx A. Matienzo notifications@github.comwrote:

> @ModalUrsine https://github.com/ModalUrsine duly noted!
> 
> Decent turnout; ~14 people!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/computeranonymous/computer/issues/185#issuecomment-27381743
> .

## 

Make your world! • http://alexglow.com
VSRE emails are cool. • http://vsre.info/

**Comment by anarchivist** [comment]
hi @alexglow! no prob - but i'm going to be away this weekend! :) maybe reach out to others on the nyc page via twitter?

**Comment by telemachus** [comment]
I made a pull request, but I'm not sure if that's the best way to RSVP any more. So, I plan to attend the December meeting, and you're welcome to add me to the list. I'm [telemachus](https://twitter.com/telemachus) on Twitter and IRC (when I'm on IRC which is spotty lately).

**Comment by anarchivist** [comment]
@telemachus Pull requests are fine, thanks!
