### ISSUE TITLE
Date/Time/Location Discussion for Portland, ME

### ISSUE THREAD

**Issue by llimllib** [computeranonymous/computer#198]
Let's figure out a date, time, and location that work for a plurality of the proposed Portland, ME meeting of Computer Anonymous. Check out [computeranonymous.org](http://computeranonymous.org/) if you forgot what it's about.

I think we should aim for the week of November 4-8. I also think we should have it in Portland, because I'm in Portland :)

So, what nights work for you on the week of November 4-8? In early voting, **November 7, 7PM at Salvage BBQ** has been the favorite. Let us know if that's not good for you!

cc: @kencochrane @johncosta @rektide @sogrady @decklin @xach @tlots @mtdonahue @statik @neruson @rlandry @justinsteele @noise @mdesjardins

People that expressed interest on twitter that I don't see on github: @BarrettSprague @pistraami @not_that_guy

Please loop in anybody else who may be interested! (Also I almost certainly forgot _somebody_ so I sincerely apologize if I did)

**Comment by llimllib** [comment]
I will wait until morning to send this out on Twitter.

We had the Django meetup at Think Tank tonight, that wasn't a bad venue? Would it maybe be good for this sort of event? It's a lot quieter than most bars, and had _tons_ of space.

Any night that week works for me.

**Comment by mtdonahue** [comment]
How about Thursday 11/7? I assume that the Think Tank will let us BYOB?

On Tue, Oct 22, 2013 at 9:53 PM, Bill Mill notifications@github.com wrote:

> I will wait until morning to send this out on Twitter.
> 
> We had the Django meetup at Think Tank tonight, that wasn't a bad venue?
> Would it maybe be good for this sort of event? It's a lot quieter than most
> bars, and had _tons_ of space.
> 
> Any night that week works for me.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/computeranonymous/computer/issues/198#issuecomment-26875220
> .

## 

+------------------------------+
 Mark Donahue
 http://www.katrinka.net
 207.370.1593 (m)
+------------------------------+

**Comment by justinsteele** [comment]
From my experience at meetups at Think Tank, yes. I'm fine having it at TT
for an initial meetup, but what does everyone think of using the meetup as
a way to also try new local pubs/bars?

Also, 11/7 is also fine with me.

Thanks,
Justin

**Comment by neruson** [comment]
11/7 sounds good. Any venue's fine with me as long as it's quiet enough that you can have a conversation without having to yell.

—

**Comment by sogrady** [comment]
Pretty sure I can do 11/7. Outside chance I get tied up in CA earlier in the week, but odds are I'll be there. As for venue, I'm down with Think Tank, a pub or wherever as long as there's beer.

**Comment by johncosta** [comment]
11/7 looks good for me.

**Comment by sto1t** [comment]
11/7 is good for me as well. I'm with neruson on the conversation compatible atmosphere.

**Comment by mpistrang** [comment]
I'm out for 11/7, but definitely keep me in the loop for the next one.

**Comment by noise** [comment]
I haven't met any of you yet but looking forward to it, thanks for the invite!

**Comment by llimllib** [comment]
I have contacted Think Tank but not received any response yet.

I think as a backup, we could use the new Salvage BBQ. It's quite spacious.

**Comment by justinsteele** [comment]
Salvage sounds good, been meaning to check it out. Also I'm assuming a
Thursday night won't be too busy.. But we'll see.

**Comment by neruson** [comment]
I've heard positive things about Salvage as well, seems like a good choice.

**Comment by rlandry** [comment]
11/7 should be OK for me but plans could change.

**Comment by llimllib** [comment]
Think Tank did get back to me, but they want to charge me and there's also the opening-the-door issue, so I think I'm going to call it for Salvage.

Anyone object?

**Comment by drtortoise** [comment]
First meeting proposed and up on website as per https://github.com/computeranonymous/computer/pull/212
