### ISSUE TITLE
pick a date to computer

### ISSUE THREAD

**Issue by tef** [computeranonymous/computer#2]
@didlix suggests every two weeks. I am ok with this. 

Is wednesday a good day for this? I can see collisions on tues/thurs/fri with other things.

**Comment by fables-tales** [comment]
@tef Wednesday (2nd october) works well for me!

**Comment by DRMacIver** [comment]
I have a monthly thing the first Wednesday of every month. This would be a non-issue if we made it the second and fourth wednesday, but if that doesn't work for people I'm also happy to just skip half of them.

**Comment by didlix** [comment]
No matter what day we pick, there will be people who cannot make it. Wednesday is my University day and I have been advised to put what I learn into practice straight away. Failing that, it was my Gym day (although the instructor has left).

**Comment by DRMacIver** [comment]
We could alternate between different days of the week?

**Comment by DRMacIver** [comment]
Proposal: We each submit recurring commitments which would prevent us from attending. We pick the Nth weekday the most people can attend. We then pick the weekday two weeks offset from that the most people who can't attend the other one can attend.

**Comment by tef** [comment]
Tell us when you are free in the next two weeks http://doodle.com/dxz7f28fh7mg4x82

**Comment by DRMacIver** [comment]
or we could do that.

**Comment by ntlk** [comment]
Wednesdays and Tuesdays totally do it for me

**Comment by drtortoise** [comment]
can this be my replacement Wenlock

**Comment by ntlk** [comment]
yes

On 25 September 2013 at 22:53:28, L. Sandvik (notifications@github.com) wrote:

can this be my replacement Wenlock

**Comment by drtortoise** [comment]
I vote Friday because all the programmers will be at silicon Drinkabout

**Comment by drtortoise** [comment]
Dammit phone autocorrect. BROGRAMMERS.

**Comment by janepipistrelle** [comment]
Friday would be best for me because Oxford. Tuesday I couldn't make because I Code Club on Wednesday and get up at the buttcrack of dawn.

**Comment by tef** [comment]
Friday will collide with a lot of things, but wed and thurs are popular. @didlix can't do wednesdays (or why we're doing this in the first place).

I am tempted to put my foot down and make a dictatorial call:

Thursday, the 3rd of October*, 6.00 onwards, at the Pembury Tavern
- It will fit everyone inside.
- They have food and drinks that will please most people
- There is overground and national rail.

If I can get a rough consensus I'll make the call tonight
- Edit: I do not have a time machine.
- Edit2: First thursday will never clash with pub standards

**Comment by tef** [comment]
@ntlk, @didlix, @DRMacIver what's your call?

**Comment by janepipistrelle** [comment]
@tef you mean October not August unless you have a time machine

**Comment by tef** [comment]
I do not have a time machine.

**Comment by tef** [comment]
(nb sarahpinder mentioned gender neutral bathrooms as a preference, the pembury has this but only the accessible toilet)

**Comment by tef** [comment]
I would also like to pick a day where it's easy to have a repeating date/time, like once a month or twice a month. We can always just pick one day _now_ and then move to a regular thing if we keep the interest. I guess we can save that decision for the first meeting

**Comment by drtortoise** [comment]
The dove freehouse on broadway market has unisex bathrooms. I like them in principle, but it always freaks me out when guys hit on me in the bathroom though.

**Comment by ntlk** [comment]
That's a shame, because I prefer unisex toilets :(

**Comment by tef** [comment]
It also seems wednesdays are less busy and won't ever clash with pub standards. Friday would be good to get away from Silicon Roundabout but i'm worried about letting it turn into a pissup/drink fest.  It seems from the straw poll, wed/thur is most popular day, tuesday too.

I'm saying next thursday at the pembury.

**Comment by ntlk** [comment]
Next Thursday at Pembury works for me

**Comment by tef** [comment]
:shipit:
