### ISSUE TITLE
Computer materials are not under a friendly license

### ISSUE THREAD

**Issue by DRMacIver** [computeranonymous/computer#20]
I suggest something creative commonsy.

**Comment by gearmonkey** [comment]
+1
I propose CC-BY-SA 3.0 http://creativecommons.org/licenses/by-sa/3.0/
thoughts?

**Comment by ntlk** [comment]
:+1:

**Comment by fables-tales** [comment]
:+1:

**Comment by gearmonkey** [comment]
so, based on this and some ##computer chat, it seems the decision is basically CC0 (http://creativecommons.org/about/cc0) or the above mentioned CC-BY-SA 3.0 

I'm on the fence as to which is better in this case, but I think it should be up to the group. we should probably have a vote or something.

**Comment by ntlk** [comment]
I'm for CC0 more than I'm happy with CC-BY-SA 3.0

**Comment by tef** [comment]
CC0 is my preferred license (I think I wrote the bulk of the text) and everyone seems happy with CC0 including the German translation 

assuming no objections can someone not on a phone add a LICENCE file and info in the footer

**Comment by tef** [comment]
Awesome
