### ISSUE TITLE
email adresses for Groups

### ISSUE THREAD

**Issue by greelgorke** [computeranonymous/computer#201]
I propose to have email adresses for each group like hamburg@comuteranonymous.org, so we can use them to create single point of contact, and more importantly local accounts on twitter for announcements and discussions

**Comment by ntlk** [comment]
:+1: from me

**Comment by SamLR** [comment]
Seems sensible to me

**Comment by tef** [comment]
ughhhh effforrrrttttt

**Comment by tef** [comment]
I propose putting a real email address or equiv on the site, rather than me having to manage forwarding addresses, and then people arguing who gets which email address. Or worse, trying to set it up to forward to multiple people

**Comment by tef** [comment]
From IRC it seems this is more than a request for email forwarding, but actual email accounts. 
- I am not an email admin or a free email provider.

I'm also too lazy to spend effort setting up and subsequently having to maintain email forwarding lists too. Give it more than a month or two and i'll reconsider, but at the moment this is a whole lot of work for vanity email addresses
