### ISSUE TITLE
Hamburg Location Search

### ISSUE THREAD

**Issue by greelgorke** [computeranonymous/computer#203]
the 6. November is it.

Where should it be?

Suggestions?

**Comment by mparramont** [comment]
Center of Hamburg? A place quiet enough to be able to talk?

**Comment by greelgorke** [comment]
btw. i whant to point to https://twitter.com/WhyComputer_HH as kindof official hamburg bird

to topic. since i can't be there on 6. November it doesn't matter to me. but i could suggest few locations in/around St. Pauli like [Feldstern](https://www.facebook.com/feldstern.hamburg) near Knust and [Cafe Absurd](http://www.cafeabsurd.de/galerie/galerie.html)

**Comment by dertseha** [comment]
I haven't been to Hamburg so far, so I'd be open for (nearly) any recommendation - but just from its pictures, Cafe Absurd looks interesting.

**Comment by mparramont** [comment]
Yup, I think the same. +1 to Cafe Absurd

**Comment by greelgorke** [comment]
so it's Cafe Absurd then

**Comment by dertseha** [comment]
What is the time frame? My flight arrives in the evening on that day - I expect to be settled and available at around 8pm.

**Comment by mparramont** [comment]
I have to do work-related stuff until 9:30pm. I can join at 10pm, but of course you can start the meeting earlier.
