### ISSUE TITLE
Minneapolis

### ISSUE THREAD

**Issue by kmarekspartz** [computeranonymous/computer#207]
> Austin and _Minneapolis_ are next

Any word on this? Or someone I can help on getting this going?

**Comment by maestrofjp** [comment]
I have a fork for Minneapolis here... haven't committed to any dates yet...

https://github.com/PyMNtos/computer/blob/gh-pages/us_minneapolis.html

**Comment by kmarekspartz** [comment]
Cool. Let's aim for October.
