### ISSUE TITLE
The harrassment policy we link to doesn't really make sense in our context

### ISSUE THREAD

**Issue by DRMacIver** [computeranonymous/computer#26]
A lot of it is about enforcement, and it's focused around more formalised events with people acting as organisers. We don't have that, which makes it harder for us to apply it. Additionally by linking to it as opposed to having our own we significantly increase the complexity of actually understanding the rules.

I think we could reasonably distil down the bits that are relevant to us with only a slight expansion of the content we've currently got: basically just elaborating on what constitutes harassment.

We also need to come up with a means of enforcement that actually makes sense for us.

**Comment by russss** [comment]
Agree.

I think "we won't invite you again" is a fine method of enforcement at the
moment. Anything more would need cooperation from the venue, and is
probably overkill.

At any rate, this policy is going to be much more valuable as an indicator
of our intentions than an actual set of rules that we follow.

**Comment by tef** [comment]
I linked to it originally as a placeholder. I think we can remove the link eventually, or better yet link to something more apt and concise. 

If everyone is happy with the rules as they stand i'm happy to remove the link.

**Comment by RHesketh** [comment]
I read over the index page and I like it a lot, I think it stands alone as-is and if there's anything that could be expanded or clarified it can be easily added in a later commit.

**Comment by russss** [comment]
I was writing a proposal but it seems I was just describing a diff, so let me put together a pull request. Seems #19 is just a subset of this, though.

**Comment by tef** [comment]
This is a long term goal (read not this week). We should remove the link as the last action, rather than immediately. 

We'll come back to this issue and review things

**Comment by tef** [comment]
#124 should close this.
