### ISSUE TITLE
@tef is tired of running the pembury meetup

### ISSUE THREAD

**Issue by tef** [computeranonymous/computer#296]
It's sorta worked, and sorta not worked, and I've become quite tired of trying to be organized once a month.
- the pembury has space but it's loud as heck
- a lot of people turn up, then go home
- the majority of people who turn up, I know already from existing social things. computer turns into cliques very quickly.

I'm not sure what to do, but I'm hoping someone else will. :-)

**Comment by bmillwood** [comment]
Would volunteer manpower help? If so then what do you need?

**Comment by ntlk** [comment]
Pembury is quite loud, but so are all other pubs on a Thursday night, sadly.

Does the meetup require any organisation? It might be that now the dust has settled a few folks will turn up whether you do anything or not. In any case, it definitely shouldn't be one person's job (single point of failure).

**Comment by bmillwood** [comment]
You'd think so, but last month tef couldn't make it and in the end precisely two people showed up and one of them was the owner of the pub (the other was me).

It is conceivable that we could meet in a non-pub, if we're that keen to avoid noise. Food would then probably need a bit more organisation.

**Comment by tef** [comment]
Posting reminders to twitter. Bugging people. Telling people about it. Making sure we have space in the pub. Introducing people to each other.

**Comment by drtortoise** [comment]
maybe we could have a special computer meet at the hackspace - not noisy, about the same areas as pembury. BYO food/drinks.

**Comment by drtortoise** [comment]
you could also look into having a computer meet at Shoreditch Village Hall

**Comment by tef** [comment]
Well right now I can't get to the pembury any earlier than 8 or 9 as my working hours have changed. Either someone else will have to step up in being a host, or we'll have to change the nature of the event.

Personally i'd like to copy SF and have brunch somewhere nice once a month.

**Comment by ntlk** [comment]
I’m gonna be there early this time, so I can be the face of computer, though I like the brunch idea

On 30 April 2014 at 17:04:31, tef (notifications@github.com) wrote:

Well right now I can't get to the pembury any earlier than 8 or 9 as my working hours have changed. Either someone else will have to step up in being a host, or we'll have to change the nature of the event.

Personally i'd like to copy SF and have brunch somewhere nice once a month.

**Comment by tef** [comment]
I've all but moved away from running this entirely. Current responsibilities include 
- [ ] irc admin
- [ ] twitter account
- [ ] domain registrar

I'm happy to hand these over, but they don't seem like priorities right now and I am committed to lazyness.
