### ISSUE TITLE
Topics of Discussion for Edinburgh Meeting 8th May 2014

### ISSUE THREAD

**Issue by leynos** [computeranonymous/computer#300]
As @johnd mentioned, we're looking at hosting some formal informal discussions around pre-decided topics to give some additional structure for the May meeting.  The topics don't necessarily have to be technical.  Since people far wiser than me are in attendance at these meetings, I'm sure the limits of any discussion on social issues surrounding computer are understood already.

Suggestions are welcome either here or via Twitter (in reply to this tweet: https://twitter.com/WhyComputerEd/status/454389978303594496).

**Comment by leynos** [comment]
Some random ideas I had:

"What will programming languages look like in 2038?"
"Is a truly semantic web actually needed?"
and "REST is an idea that has possibly had its day"

Of course, we could also go with the format "Why _x_ sucks", picking a different _x_ every month (as suggested by @johnd).

**Comment by johnd** [comment]
I'm happy to lead any kind of ops/sysadmin/devops-y discussion - current state of hosting, config management, cloud providers, etc?

Perhaps: 'the cloud: actual useful term or pointless marketing bullshit'?

**Comment by leynos** [comment]
I think there's a lot of mileage to be had out of hosting and config management discussions.  (Subjects I am interested in, but, unfortunately have little practical experience of).

**Comment by johnd** [comment]
Azz on the main ##computer IRC chat also suggested "interesting stuff you've broken" as a discussion topic.

**Comment by marksutherland** [comment]
I can't make it I'm afraid, but how about "The Internet is Dead", in light of the corporate balkanization, net neutrality and privacy issues that I'm sure we're all familiar with? :)

**Comment by johnd** [comment]
As we approach the next meeting, I suggest that we leave this open until the start of the meeting and then pick a topic based on who's there and what we're interested in.

**Comment by johnd** [comment]
I'm closing this and opening a new issue for the June meeting.
