### ISSUE TITLE
no one showed up to the last Boston event besides me?

### ISSUE THREAD

**Issue by mmautner** [computeranonymous/computer#303]
Kinda sucked :/ I went to Bukowski's and hung out for 15-20 minutes, tweeted some of the organizers, but none of them could make it by the sound of it. Next month?

**Comment by mattkane218** [comment]
Hey, it looks like people were there [in the back?](https://twitter.com/ericwbailey/status/461653690630557696)

Unfortunately I did not see your Tweet until later that night. Since I'm actually rarely at meetups, I should probably take my name off the list of organizers.
