### ISSUE TITLE
Discussion topics for June Computer Anonymous Edinburgh meeting

### ISSUE THREAD

**Issue by johnd** [computeranonymous/computer#307]
I can't make the June meeting, which makes me sad. But you probably can and you should suggest topics for discussion here.

Please see #300 for the previous month's suggestions - in the end we mostly talked about cloud things.

**Comment by johnd** [comment]
One thing that we did touch on a bit last month was how to reach out to groups that don't come to the traditional tech groups/meetups. Maybe more consideration there on working out something we can actually do?

Also, I still like the idea of a day trip away somewhere, perhaps in July, maybe the details on that could be hammered out?

**Comment by jarofgreen** [comment]
"Let's stop bashing PHP" - this is partly tongue in cheek, but mostly serious. As a tech industry we are terrible for hating on a sub group of people, and setting up divisions. This hardly contributes to a welcoming & inclusive community. Let's take the question from the blog post I mentioned last time that challenged people to make a community without drink or negativity and seriously discuss it.

(Tho I also can't make June's meeting.)

**Comment by johnd** [comment]
At the same time, it's absolutely impossible to have any kind of meaningful debate or discussion without being able to criticise things, and criticism - however well-intentioned - will always be perceived as negativity by people who are closely tied to the thing being criticised.

@jarofgreen: do you have a link to that blog post? I can't see it on the previous discussion (#300) and it'd be nice to have it in here anyway for ease of finding in the future.

**Comment by jarofgreen** [comment]
Well, yes, but there is constructive criticism and there is nasty digs. I will happily discuss PHP's warts with another PHP Programmer in detail, but ppl making cheap nasty dismissive "jokes" and put downs is what I'm talking about. Quite frankly, some of the chat at the last meetup was the latter.

**Comment by jarofgreen** [comment]
And that's not to start an accusatory discussion, I'm not so interested in naming names, however I am interested in a serious discussion about how tech sub-culture snobbery adds to the impression that this is a "nasty" community.
