### ISSUE TITLE
London Groups

### ISSUE THREAD

**Issue by squirmelia** [computeranonymous/computer#320]
I am just wondering if we should combine some of the London groups, or at least stop having four?

As far as I am aware:

East London were meeting every month at the Pembury, Hackney.

"West" London met at the Mad Hatter (Southwark) twice, the Rylston (Fulham) once, and most recently at the Willow Walk (Victoria) once. 

Central London met once at the Holborn Whippet (Holborn).

North London have never met.

**Comment by DRMacIver** [comment]
Seems eminently reasonable.

**Comment by squirmelia** [comment]
I've changed the UK_London to be listed as the active London group, and put the rest into an inactive section. If these become active again, this can of course be changed again.

**Comment by KakeLP** [comment]
I've added notes on all the inactive pages, pointing people at the main London group. I thought this was a good idea since people may have had the individual pages bookmarked, or come across them via Google.
