### ISSUE TITLE
Page Builds Failing

### ISSUE THREAD

**Issue by flowerhack** [computeranonymous/computer#339]
Got this in my inbox:

"The page build failed with the following error:

The custom domain for your GitHub Pages site is pointed at an outdated IP address. You must take immediate corrective action to ensure that your site remains available after December 1st, 2014. Additional details can be found at https://github.com/blog/1917-github-pages-legacy-ip-deprecation. For more information, see https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages."

I'm not sure who's got access to our domain provider, so, pinging probable folks: @tef @ntlk @didlix @drtortoise 

Apparently new updates to the site won't be visible until this is fixed :(

Many thanks in advance for whoever can look into this!

**Comment by tef** [comment]
It's me i'm the lazy domain admin. I've edited the zone files _blech_ and "Changes will take about 3 hours to propagate due to standard DNS propagation delays."
