### ISSUE TITLE
The website hasn't updated, is jekyll broke?

### ISSUE THREAD

**Issue by llimllib** [computeranonymous/computer#340]
If you go to http://computeranonymous.org/us_portland.html, you'll see that it still lists details for November, not December as is current in the repository

**Comment by flowerhack** [comment]
D:

It looks like it was broken for a bit due to this nonsense https://github.com/blog/1917-github-pages-legacy-ip-deprecation

I just merged another PR and it seems to have updated Portland's page too.  So sorry about that; I should've seen it!

**Comment by llimllib** [comment]
Thanks for fixing!
