### ISSUE TITLE
Gender in German

### ISSUE THREAD

**Issue by joliss** [computeranonymous/computer#37]
Likely for @mortice, @fronx, @lucaspinto

The German translation loses all the nice inclusive flair of the original by using exclusively masculine nouns (Unternehmerstammtisch instead of Unternehmer_innenstammtisch, or however you want to spell it, etc.).

Wanted to open this just FYI -- I'd send a PR, but I don't live in Berlin, so I feel like it's not really "my" page to meddle with. Feel free to close this issue as you please.

**Comment by tef** [comment]
The german translation is openly in need of help :+1:

**Comment by joliss** [comment]
Thanks @fronx!
