### ISSUE TITLE
May I have a commit bit?

### ISSUE THREAD

**Issue by llimllib** [computeranonymous/computer#379]
You all have generally been great at merging my us_portland requests, but it'd be easier if I could just push them. I have no interest in editing anything else.

**Comment by flowerhack** [comment]
I'd actually tried to give you a commit bit a few months ago, but I don't seem to have the authority to do such a thing :(

@DRMacIver @ntlk @tef , any chance you could do this?  (Also, if you'd feel comfortable with giving me an owner bit, I'd happily take care of stuff like this in the future; scout's honor that I will mostly continue to do what I've been doing :P)

**Comment by tef** [comment]
Hi

@flowerhack you should have owner priv,@llimllib you should have member priv

**Comment by flowerhack** [comment]
perfecto, thanks!

**Comment by llimllib** [comment]
Sorry to be a bother, but I'm not able to commit

**Comment by DRMacIver** [comment]
You should be able to now.
