### ISSUE TITLE
Dead link, alternatives?

### ISSUE THREAD

**Issue by johnd** [computeranonymous/computer#385]
The link at the end of the rules 'specific resources for various issues' / http://superopinionated.dreamhosters.com/101-a-tron/ is totally dead, DNS gone, and I'm not sure what it contained now.

If it was a list of resources that might've included a nice primer on why we should default to believing women when they make claims of rape or sexual assault, that would've been really handy tonight.

Does anything have a replacement link, or should we just drop it?

**Comment by flowerhack** [comment]
Hey there!  Thanks for pointing this out.

Poking the web archive, it looks like it indeed had some resources on such topics: http://web.archive.org/web/20141116222730/http://superopinionated.dreamhosters.com/101-a-tron

I think any of (a) linking to the web archive post, (b) asking the OP if we could mirror the original post on computeranonymous.org, or (c) coming up with our own list of resources would be reasonable.

I like (b) best, so I'll probably pursue that course of action tomorrow—unless you have another idea/suggestion/etc, I'm pretty flexible on this :)

Will update this issue accordingly.

**Comment by johnd** [comment]
I am all for mirroring that list of resources, if you can get in touch with the original poster. Looks like her Twitter bot is gone and her own account suspended. :(
