### ISSUE TITLE
Move to computeranonymous.org, in preparation for split repos

### ISSUE THREAD

**Issue by tef** [computeranonymous/computer#45]
1. Edit CNAME to point to computeranonymous.org, update twitter, github bio
2. Change computer.twentygototen.org to redirect to computeranonymous.org
3. Rename the main repo in computeranonymous.github.io, instead of just computer, (I'm somewhat sad about this)
4. Create repos inside the computeranonymous organization for regional meetups that want them: This means that they can set their own CNAME, (including subdomains of computeranonymous.org), but by default, computeranonymous.org/reponame/ will work.

**Comment by tef** [comment]
I also registered computeranonymous.org and .com

**Comment by russss** [comment]
Yes, I think this is a good idea because the number of small pull requests on the main repo is getting substantial now...

**Comment by tef** [comment]
I'm thinking i'll do this on sunday to minimise disruption

**Comment by tef** [comment]
Sunday/Friday, whatever. Right, i've edited the cname, changed the dns of computer.twentygototen.org, updated the CNAME file, and set up redirects. Now waiting for github to behave

**Comment by ntlk** [comment]
This is now done, innit
