### ISSUE TITLE
Accessability issues for venue

### ISSUE THREAD

**Issue by adacable** [computeranonymous/computer#48]
The site urrently states nothing about acessability for meetups: We should have some guidelines about choosing places which are wheelchair or stick acessable, have no loud/Thumpy music and are blind/etc freindly. 

Proposed changes: A section, possibly on a second page for organizers, recommending some guidelines on choosing a location.

 [Here(pdf)](http://www.unitedspinal.org/pdf/DisabilityEtiquette.pdf) is a good guide for starters, but we should also have some notes about placement in relation to pubic transport(not all coders are rich) and lighting/etc on routes in between the venue and this transport for women and other groups who have reason to fear walking in cities.

**Comment by AgentAntelope** [comment]
+1 on this as someone who may well be attending on crutches if I'm not having a good day.

**Comment by tef** [comment]
:+1:

**Comment by tef** [comment]
(We need guides for meeting organizers on a more general note)

**Comment by tef** [comment]
We have some information on running a venue. If we can fix a specific thing, open a PR. I'm closing vague or open ended issues.

**Comment by Skud** [comment]
Potentially useful blog post I wrote: [making your events more accessible is not that hard](http://infotrope.net/2014/11/17/making-your-events-more-accessible-is-not-that-hard/)
