### ISSUE TITLE
Merchandising. i.e people already want t-shirts and stickers, despite no meetings happening

### ISSUE THREAD

**Issue by tef** [computeranonymous/computer#63]
This is pre-emptive, but to keep a record of what's coming up in discussions, i've opened this bug

A t-shirt has been requested:
"Computer Anonymous
computering is not a competition" 

People on twitter have asked for laptop stickers.

We don't really have any logo, or logo type beyond the twitter avatar 
![computer](https://f.cloud.github.com/assets/56231/1233455/d5ccd47e-2929-11e3-98e0-ea1f3f8eaf41.png)

**Comment by AgentAntelope** [comment]
I like that logo, honestly. I'd wear it on a shirt.

**Comment by tef** [comment]
For the record the font is vt220  http://asdasd.rpg.fi/~svo/glasstty/

**Comment by gearmonkey** [comment]
I kinda think no merch till there's actually been a meetup, somewhere?

**Comment by tef** [comment]
Of course. As mentioned this is preemptive. :-)

**Comment by ntlk** [comment]
SENSIBLE IS BORING

**Comment by adacable** [comment]
If I were to rock up with some Stickers, they'd be cool, though? (I have sticker paper, and a printer)

**Comment by tef** [comment]
I was thinking 

## Option A

A sticker that says 'computer'

## Option B

Three Stickers: Computer, Computer ? , and Computer :-(

## Option C

One sticker with:

Computer Computer? Computer :-(

I'm leaning towards Option B for labels/stickers for the meetup, and Option C for laptop stickers

**Comment by tef** [comment]
I've had another person ask me for laptop stickers today. They also offered me temporary tattoo paper for the meetup

**Comment by AgentAntelope** [comment]
I like both options B and C.

**Comment by adacable** [comment]
I have inkjet compatible sticker paper(I think. may still be up north). so that could be a thing. Of not amazon stocks bumper sticker paper(ie:glossy feel/look, waterproof).

Also, if the labels/stickers for the meetup you mention are like for name badges, can I request that we have space for a twitter handle and a field for pronouns?

**Comment by sjmarshy** [comment]
if needed, I have some (pretty rusty) design skills, I'm liking the idea of option B

**Comment by igalic** [comment]
speaking of logos and that, we should set the @WhyComputer avatar for the GitHub organization

**Comment by fables-tales** [comment]
![computer](https://f.cloud.github.com/assets/96662/1249452/96c38594-2ae0-11e3-99de-bca0e1e65e0a.png)

Here is a design for 4cm by 2cm sticker that I'm thinking about getting printed. What do people think, would anyone other than me use one?

**Comment by tef** [comment]
um, not really. I'd stick to the nostalgia and text like designs in monochrome or amber on black

**Comment by adacable** [comment]
@tef +1

**Comment by sjmarshy** [comment]
I was thinking something along these lines. Super quick sketches so imagine them in solid green/amber on black using mono fonts. 

http://i.imgur.com/NkdTURT.jpg

**Comment by adacable** [comment]
???
![computerlogo](https://f.cloud.github.com/assets/1273690/1252150/53b151ac-2b42-11e3-9bec-9f2d7d80f806.png)

**Comment by tef** [comment]
https://twitter.com/aldroid/status/385826165660729344 i liked this

**Comment by tef** [comment]
I'm generally more keen on plain text stickers, than simple line work or artwork, because it's just straight forward

**Comment by gearmonkey** [comment]
:+1: Would make a great shirt.

**Comment by adacable** [comment]
:+1: to the sticker from twitter. Can we get the artwork at high enough res to go on a t-shirt/medium sized sticker?

**Comment by tef** [comment]
http://imgur.com/a/A7UAj current things i'm going to buy.

**Comment by tef** [comment]
_ish_

I'm thinking a clear sticker with 

```
Computer.

Computer ?

Computer :-(
```

and an orange on black (eat it screen screen weenies)

```
comput
er ano
nymous
```

**Comment by didlix** [comment]
Out of everything I have seen in this thread, this is (in my opinion) the best:

![computer](https://f.cloud.github.com/assets/56231/1233455/d5ccd47e-2929-11e3-98e0-ea1f3f8eaf41.png)

It would go great on a black t-shirt, and work well with moo.com stickers.

**Comment by didlix** [comment]
@tef :+1:

**Comment by didlix** [comment]
https://twitter.com/aldroid/status/385826165660729344

I dislike this on the basis that it has a person in it and all gender war will break out and destroy civilisation.

**Comment by ntlk** [comment]
I'd like a separate repository for sticker etc. designs, where people can upload their own in different resolutions and we can have decentralised means of production

On 8 October 2013 at 16:29:06, Rachel Graves (notifications@github.com) wrote:

Out of everything I have seen in this thread, this is (in my opinion) the best:

**Comment by ntlk** [comment]
Hey, maybe they are different gender to the one they present, huh? :P

On 8 October 2013 at 16:31:21, Rachel Graves (notifications@github.com) wrote:

https://twitter.com/aldroid/status/385826165660729344

I dislike this on the basis that it has a person in it and all gender war will break out and destroy civilisation.

**Comment by didlix** [comment]
See, the gender war has started.

**Comment by didlix** [comment]
_gets in a bunker_

**Comment by ntlk** [comment]
:D

**Comment by tef** [comment]
Suggestion for Sticker 1: Rectangular on clear vinyl

http://i.imgur.com/9ODotT0.png

**Comment by ntlk** [comment]
liek

On 8 October 2013 at 16:41:39, tef (notifications@github.com) wrote:

Suggestion for Sticker 1: Rectangular on clear vinyl

http://i.imgur.com/9ODotT0.png

**Comment by seubert** [comment]
Looks gooood

—

**Comment by didlix** [comment]
Not hugely keen, maybe because of the blur.

**Comment by tef** [comment]
Option 2: http://i.imgur.com/qRI1ENZ.png Square sticker orange on black.

**Comment by ntlk** [comment]
I like it better, but better still would be a shared place with all the designs so people can print the ones they like. You know, so don't have to argue which is best :)

On 8 October 2013 at 16:49:57, tef (notifications@github.com) wrote:

Option 2: http://i.imgur.com/qRI1ENZ.png Square sticker orange on black.

**Comment by tef** [comment]
http://i.imgur.com/1UxEx6b.png @didlix now with less blur!

**Comment by tef** [comment]
This is me doing my own print run, @ntlk, and i keep redrawing it each time.

**Comment by ntlk** [comment]
k

On 8 October 2013 at 16:56:32, tef (notifications@github.com) wrote:

This is me doing my own print run, @ntlk, and i keep redrawing it each time.

**Comment by tef** [comment]
re: https://twitter.com/aldroid/status/385826165660729344 i don't think we have copyright, so it's a fun meme but not a sticker.

**Comment by tef** [comment]
I have ordered 200 stickers.

100 of http://i.imgur.com/1UxEx6b.png on clear vinyl
100 of http://i.imgur.com/qRI1ENZ.png on black glossy vinyl

**Comment by ntlk** [comment]
AWW YEAH

On 8 October 2013 at 17:09:49, tef (notifications@github.com) wrote:

I have ordered 200 stickers.

100 of http://i.imgur.com/1UxEx6b.png on clear vinyl
100 of http://i.imgur.com/qRI1ENZ.png on black glossy vinyl

**Comment by tef** [comment]
Stickers have been dispatched. May arrive tomorrow or next week.

**Comment by igalic** [comment]
\o/

**Comment by tef** [comment]
I have stickers. 
![image-2](https://f.cloud.github.com/assets/56231/1326042/1553507c-34d9-11e3-87da-b0a6bea6d440.jpeg)
![image](https://f.cloud.github.com/assets/56231/1326043/1956d8f6-34d9-11e3-8d44-5916758e0569.jpeg)

**Comment by ntlk** [comment]
YES

On 14 October 2013 at 15:21:43, tef (notifications@github.com) wrote:

I have stickers.

**Comment by gearmonkey** [comment]
:yellow_heart: :+1:

**Comment by seubert** [comment]
BEAUTIFUL

**Comment by timcowlishaw** [comment]
:heart: :heart: :heart: thanks @tef @ntlk!

**Comment by ntlk** [comment]
It's all @tef's work

**Comment by tef** [comment]
The source images I used along with vague dimentions and typefaces are in the repo too.

**Comment by tef** [comment]
I'm going to consider this closed for now
- We have stickers. Source materials are in github.
- No other plans made.
