### ISSUE TITLE
Consistency in website 

### ISSUE THREAD

**Issue by adacable** [computeranonymous/computer#66]
Proposal: Either provide a template for new pages with a common nav/header/footer/etc or implement a static site generator to simplify adding new pages.

Reasoning: Looks like we're going to be adding another few pages at the least, and adding things like text size/color buttons, common markup for accessibility would be a lot easier with at least a template. 

A static site generator would be even easier, meaning that we wouldn't need to upadate every page if we decided to add a nav bar or something later. 

Counter arguments: Possibly harder for people to contribute(though I think most people will find it easier to edit just the important text rather than writing a full page with all the header/etc), and probably a bit of work.

**Comment by russss** [comment]
Yup. Since GitHub Pages gives us Jekyll for free, we should probably use that. We can literally just use it as an HTML templating system, which should make it dead easy to switch over, and provide the additional bonus of us not having to hear about @tef's views on Markdown.

**Comment by adacable** [comment]
Oh, come on, It's so much more natural than html ;)

**Comment by tef** [comment]
I am happy with the current mess. I am willing to wait a _whole_ week before replacing things with a shell script.

**Comment by tef** [comment]
N.b. We're planning to split out the site into separate repos, so templating might not be so easy

**Comment by adacable** [comment]
You have a good point. Going to close this then.

**Comment by tef** [comment]
Oops. 

I think we need to re-open this issue soon, perhaps having a simple repo to clone, or shared resources, or some way to make it easy to generate pages.

This may involve moving off gh-pages
