### ISSUE TITLE
Use of pronouns

### ISSUE THREAD

**Issue by urschrei** [computeranonymous/computer#67]
I'd like to propose a brief section about pronouns in the code of conduct. Maybe something like "Please don't assume that everyone would like to be referred to as 'he' or 'she' – respect people's choice of pronoun, and if you're unsure, ask."

**Comment by adacable** [comment]
As a (non binary) trans\* person who plans to attend, I think this should be linked elsewhere or in the code of conduct, like all other issues from race to disability are. 

That said, the current code of conduct does not have anything about this issue and I'd really like our code to include it. (in fact, people misgendering me makes a space unsafe)

I think it is important that some more specific codes(for example, dealing with disabled people) are linked or possibly $issue 101 posts if anyone has them?

**Comment by tef** [comment]
We're trying to err on the side of brevity in the current code of conduct, rather than a comprehensive list of how to behave and act.  (Note: I'm not going to close this issue, this is important)

The problem with enumeration of good and bad behaviours is that it is endless. If we can find a good and succinct way to capture this and related problems, i'll be happy to merge :-)

Edit: I think linking to these issues is probably the best course of action. We don't have the space for nuance.

**Comment by adacable** [comment]
Proposal: Links to good quality best practice guides on issues, in their own page or section, as recommended reading for organizers, and as an opportunity for people to educate themselves if they want, and somewhere to point people if they really do muck up unintentionally.

Reasoning: We can't educate someone in how to be a perfect ally to every cause. It is impossible, and made more so by our restrictions, and also not our mission. 

We do, however need to have somewhere we can point people at when they misgender me, call somone a bitch, or make a racist comment. And it would be nice to have it on the computer website so we're not accused of being SJ warrior feminazi furries. (not that anyone attending would do, but people act weird when called out.)

Organizers need to be a bit hotter on their issues however: when someone comes to them and says "x did y", they need to know why y is bad, how bad it is, and how they can help. 

Also: it allows oppressed groups to work their own issues out, and we don't have to check every thing we write: we just grab posts written by the group.

**Comment by seubert** [comment]
@drcable I agree with you on pretty much everything, but don't feel equipped to add anything succinct and I don't know of a great resource to link to. Can you give us some suggestions?

**Comment by tef** [comment]
+1 for resources for organisers, especially being more thorough or detailed
+1 for adding something about your behaviour might be called out, so you should listen, etc

**Comment by ntlk** [comment]
I think having more complete resources for organisers is a great idea

**Comment by adacable** [comment]
[This(pdf)](http://www.unitedspinal.org/pdf/DisabilityEtiquette.pdf) was recommended to my on disability, and covers a lot of the ground. 
[this](http://tranarchism.com/2010/11/26/not-your-moms-trans-101/) is my preferred trans\* 101, though you may find it a bit aggressive. Anyone else non-cis want to chuck something in the ring? Or cis people who've had something recommended to them?
Race wise, I simply have no idea, and these posts are really long. We really need better resources. 
Proposed topics list:
- race 
- QUILTBAG
- Ablism
- What else

(plug: If any LG people are reading this, [QUILTBAG101](https://github.com/drcable/QUILTBAG101) would be a decent thing to link to, but we're missing feedback from you for [your section](https://github.com/drcable/QUILTBAG101/blob/master/4.mdl) (and no, It's not dead.))

**Comment by janepipistrelle** [comment]
I have a bit of experience with this from efforts to make a roller derby league more inclusive–am digging through stuff for good (and concise) linkage.

**Comment by ntlk** [comment]
I don't know how deeply we want to get into explaining trans\* 101, but we could say something like:

> Don't harass people. Don't make exclusionary jokes. Don't even make them "ironically". Use person's preferred pronoun (if you're unsure which one to use, ask).

**Comment by janepipistrelle** [comment]
I think that's great for the actual policy as a brief reminder.

linkage for organisers would still be handy, though?

**Comment by adacable** [comment]
On 30/09/13 11:32, ntlk wrote:

> I don't know how deeply we want to get into explaining trans\* 101, but we could say something like:
> 
> > Don't harass people. Don't make exclusionary jokes. Don't even make them "ironically". Use person's preferred pronoun (if you're unsure which one to use, ask).
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/computeranonymous/computer/issues/67#issuecomment-25350806
> 
> A bit more general: "Don't make assumptions. Don't assume
> peoples gender(or their preferred pronouns), sexuality, abilities, or
> what is damaging to them. There are few wrong questions as long as they
> are respectfully asked."

## 

---

Thomas Walpole, Maker
drcable.org @drcabl3 drcabl3.tumblr.com

**Comment by adacable** [comment]
On 30/09/13 11:32, ntlk wrote:

> I don't know how deeply we want to get into explaining trans\* 101, but we could say something like:
> 
> > Don't harass people. Don't make exclusionary jokes. Don't even make them "ironically". Use person's preferred pronoun (if you're unsure which one to use, ask).
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/computeranonymous/computer/issues/67#issuecomment-25350806
> 
> agree. The trouble is you need to much changing to be able to act
> safeley towards people- because "normal" is so hostile.

## 

---

Thomas Walpole, Maker
drcable.org @drcabl3 drcabl3.tumblr.com

**Comment by ntlk** [comment]
"Don't assume person's gender (or their preferred pronouns), sexuality or abilities." <- would be more concise way to express it that I think still captures the spirit

**Comment by adacable** [comment]
On 30/09/13 11:51, ntlk wrote:

> "Don't assume person's gender (or their preferred pronouns), sexuality or abilities." <- would be more concise way to express it that I think still captures the spirit
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/computeranonymous/computer/issues/67#issuecomment-25351606
> 
> @ntlk

"Don't assume person's gender, their preferred pronouns, sexuality,
abilities or anything else personal. If in doubt ask respectfully."

I think the asking is important, and as is the "anything else". Because
ours are not the only issues.

## Also, it scans better with no brackets.

---

Thomas Walpole, Maker
drcable.org @drcabl3 drcabl3.tumblr.com

**Comment by tef** [comment]
"Don't assume person's gender, their preferred pronouns, sexuality,
abilities or anything else personal. If in doubt ask respectfully."

I think this covers a lot, but I'm thinking we can refine this a little more

**Comment by adacable** [comment]
On 30/09/13 16:25, tef wrote:

> "Don't assume person's gender, their preferred pronouns, sexuality,
> abilities or anything else personal. If in doubt ask respectfully."
> 
> I think this covers a lot, but I'm thinking we can refine this a little more
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/computeranonymous/computer/issues/67#issuecomment-25372508
> 
> This was just going in the PR. Not a lot I can think to cut?

## 

---

Thomas Walpole, Maker
drcable.org @drcabl3 drcabl3.tumblr.com

**Comment by urschrei** [comment]
Is there a reason we aren't saying "a person's"?

**Comment by tef** [comment]
Open a PR for this line, we'll refine it in there.

**Comment by tef** [comment]
We've got something in the rules now, Closing. Open a new issue with refinements.
