### ISSUE TITLE
ICal for meetups?

### ISSUE THREAD

**Issue by tef** [computeranonymous/computer#80]

**Comment by ntlk** [comment]
:computer: :calendar:

**Comment by adacable** [comment]
Google calender? Has Ical export and a lot of people use google anyway?

**Comment by palfrey** [comment]
Alternately, we can provide iCal files somehow... most trivial way to do that would be to actually just generate the daft things and store them in the repo, but iCal is a horrible format to work with. Things like [jQuery iCalendar](http://keith-wood.name/icalendar.html) might make this more feasible though.

_Update_: Having thought about that, it doesn't work. jQuery Calendar makes it really easy to add individual events, but there's no way to give a usable persistent URL for event feeds to 3rd parties without either server-side support or actual iCal files. There's a slightly mad thought that says "store event data in some more human-readable form, and then do offline iCal generation" but this stops people from being able to just edit stuff on Github, which is bad. Not sure quite how to do this...

**Comment by tef** [comment]
I've made a calendar for East London. I'm going to let each event organiser sort their own stuff out

**Comment by ntlk** [comment]
:+1:

**Comment by didlix** [comment]
There is a gem (iCalendar, I believe) for ruby which makes creating iCalendar files trivial.

**Comment by ntlk** [comment]
@didlix not sure it would work with jekyll and gh-pages, in any case I think each meetup should find a way to handle this on their own

**Comment by didlix** [comment]
@ntlk almost certainly not.
