### ISSUE TITLE
What we can learn from last night

### ISSUE THREAD

**Issue by tef** [computeranonymous/computer#92]
https://twitter.com/jwreschnig/status/384769554850648064

"Nevermind, cishets concern-trolled out a trans person and then said he "overreacted." @WhyComputer's still pretty fucking toxic."

Last night, IRC went real bad, real quickly, here's the scrollback:
https://gist.github.com/tef/6e830e4b0fb4a01d5ca1

The summary from my perspective is that someone asked a question which was indistinguishable from trolling, It then spiralled out of control.

Worse still, people rose to my defense and have been telling them i'm a nice guy and talking about my intent without realising it's a standard way of dismissing complaints about sexist remarks.

I don't want a hostile IRC channel but I don't want to silence outrage either. We need to ensure that people who call us out aren't silenced, but listened to. Both of these things are really hard.

As I said last night, computer anonymous is an experiment, we're going to fuck up, we have lots to learn, so it's time to listen, not to act. I have no fucking idea what i'm doing so please don't be dismissive of criticism

**Comment by tef** [comment]
See also #91

**Comment by DRMacIver** [comment]
I think this probably provides quite a good argument for public logging. When we fuck up it's better to fuck up visibly in public and own our mistakes than it is to try and cover them - it just creates confusion. A lot of people had to ask for scrollback and I think if we're doing that then it's basically like public logging but less inclusive.

It's also nice to have more visibility of the fact that we're actually trying to fix things, which currently isn't obvious if people decide we're terrible people and leave as a result.

**Comment by ketsuban** [comment]
Perhaps we should have some sort of infrequently-asked-questions page to provide honest answers to these indistinguishable-from-trolling questions, such that we can reasonably assume anyone asking them is in fact trolling?

**Comment by public** [comment]
If people don't feel comfortable coming we shouldn't feel obligated to make them feel comfortable. We need to establish why they don't want to, and see if changing to accommodate that would make us more inclusive or not. In this case I think it's clear that trying to be more accommodating to cis white guys who superficially appear to have good intentions might not be the best use of our time. (And FWIW I say that as a cis white guy.)

We should definitely avoid tone-policing anyone (telling people to be patient counts as this imo) and some mention of the classic blunders (e.g. things here http://geekfeminism.wikia.com/wiki/Category:Silencing_tactics) in this space on the site might be useful.

**Comment by rboulton** [comment]
@Ketsuban that seems like a very good approach; if there's any doubt, a single line response in IRC pointing to the appropriate page should then be the standard response.  I don't think it needs to be a list of infrequently-asked-questions; just a couple of examples of questions which are likely to cause problems but can also be asked with ignorant good intentions.

One think touched on in the IRC discussion (which I haven't read all of) was whether this is meant to be a support group, or trying to educate people.  I think it should be a support group, but having links ready to help people educate themselves would help a lot.

**Comment by adacable** [comment]
@DRMacIver re:logging I posted a comment requesting reopening with some possible fixes to the "public record" problem while keeping some teeth to it. The comment is in the original issue.

@Ketsuban I think we should move some stuff around to make it more central, not on a secondary FAQ. Our premise should be "this is a safe space for oppressed groups" and we should let everything else flow from there. 

@public I don't think that being comfortable to white cishet guys should be a priority, and we should be obliged to make oppressed groups fee comfortable over privileged people. You guys have the rest of the tech community to feel comfortable in. This is(to me) about a space where I can rock up in a skirt(disclosure:Non-binary MAAB) and not get stared at, asked what's in my pants, or called a dude. 

Obviously, we shouldn't make decisions to actively get rid of chishet white men who behave well, or only mess up occasionally(and I'd like to congratulate @tef here, who has, in the cold light of day, done everything he could to calm things down and raise our voices). But we should always prioritize making oppressed groups feel comfortable over cishets.  

The tone policing last night was strong in evidence and the only way to fix this is education and people telling others not to tone police. This wasn't in evidence last night and needs to be, possibly through an "offifical" set of mods or mediators.

**Comment by ntlk** [comment]
I'm not sure I agree we even _can_ create an entirely safe space. @janepipistrelle, could you find that article you've shared with me once about safe spaces? The gist of it was that it's a fuzzy term, and means different things to different people, so it's not necessarily a realistic expectation in general groups, but maybe something that can be achieved in small, focussed ones.

On 1 October 2013 at 09:59:25, Thomas Walpole (notifications@github.com) wrote:

@DRMacIver re:logging I posted a comment requesting reopening with some possible fixes to the "public record" problem while keeping some teeth to it. The comment is in the original issue.

@Ketsuban I think we should move some stuff around to make it more central, not on a secondary FAQ. Our premise should be "this is a safe space for oppressed groups" and we should let everything else flow from there.

@public I don't think that being comfortable to white cishet guys should be a priority, and we should be obliged to make oppressed groups fee comfortable over privileged people. You guys have the rest of the tech community to feel comfortable in. This is(to me) about a space where I can rock up in a skirt(disclosure:Non-binary MAAB) and not get stared at, asked what's in my pants, or called a dude.

Obviously, we shouldn't make decisions to actively get rid of chishet white men who behave well, or only mess up occasionally(and I'd like to congratulate @tef here, who has, in the cold light of day, done everything he could to calm things down and raise our voices). But we should always prioritize making oppressed groups feel comfortable over cishets.

The tone policing last night was strong in evidence and the only way to fix this is education and people telling others not to tone police. This wasn't in evidence last night and needs to be, possibly through an "offifical" set of mods or mediators.

**Comment by adacable** [comment]
I have thoughts on this and partially agree, but also have a lecture in 50 mins and have stuff to do before it.

**Comment by public** [comment]
@drcable I agree. Sorry if that wasn't clear from what I wrote :)

(Damn you GitHub email replies.)

**Comment by adacable** [comment]
@public

Sorry, I thought you might bahe been arguing that we shouldn't feel obliged to make non-privileged people welcome.

**Comment by janepipistrelle** [comment]
@ntlk will look for it. too.many.computer. I agree that I'm not sure we can make this fit the formal definition of a safespace (if there is one).

I agree that making things comfortable for white cishet guys should NOT be our priority as society overwhelmingly does a good job of that already (speaking as a white, cishet). This is about making everyone else feel comfortable. If it helps I am willing to take a more active role but I'm not in London.

**Comment by adacable** [comment]
there are to my mind, two kinds of safe spaces:
- those which everyone knows what they're talking out so fuckups are highly unlikely
- those where people feel that fuckups will be dealt with cleanly and quickly, with no trauma for them. 

We're obviously not going to create the first- but the second is kinda a minimum for many people to be able to attend in a meaningful fashion(express themsevles, speak, etc). This is what I refer to when i say safe space unless I say otherwise. 

I think we can make that.

**Comment by janepipistrelle** [comment]
agreed.

**Comment by AgentAntelope** [comment]
+1

**Comment by seubert** [comment]
@drcable Thanks for all your comments here, deeply appreciated.

I compounded the problems after tef left the conversation and I apologize for that. I will take this and learn from it and I, at least, will have 0 tolerance for concern trolling, whether explicit or not.

**Comment by adacable** [comment]
:+1:

**Comment by tef** [comment]
I think I can close this issue now, and reopen it if necessary.
