### ISSUE TITLE
Remove names from the front page

### ISSUE THREAD

**Issue by tef** [computeranonymous/computer#94]
We don't want to list people on the front page, we should move the git volunteers to a seperate page, with useful links to tutorials, a guide to what PRs get merged easily, and the list of people who have voluntereed

**Comment by ketsuban** [comment]
Rebleeping from IRC: I suggest an e-mail inbox with read access shared by git volunteers. The site would read something like "If you aren't familiar with git and/or Github, e-mail &lt;address&gt; and someone will get in touch."

**Comment by igalic** [comment]
http://librelist.com/ might be a good place for that kind of contact email.

**Comment by tef** [comment]
I'm unhappy about using a generic email because we won't know who is handling it. I would rather have a list of humans and a variety of contact methods.
