### ISSUE TITLE
What is Computer? Nobody knows.

### ISSUE THREAD

**Issue by tef** [computeranonymous/computer#97]
"i think you’re going to get to pick quickly what the point of computer is, because there’s several different (competitive?) intents"

"the tension between this being a space for education, and a safe space for those who are sick of having to educate constantly."

I think we need to be clearer that computer is first and foremost a social group
- avoiding using the term "safe space", which is a rather overloaded term with many conflicting interpretations
- we're not an outreach group (It's important, but we don't have the focus, time, or resources to live up to this goal fully)
- we're not an educational group (It is also important, but again that's not what we're here to do)

I think It's about having a tech related meetup, with good people, and having a code of conduct.

I'm thinking we need an FAQ

**Comment by adacable** [comment]
Having a code of conduct is not an end in itself. you have a code of conduct to encourage/discourage behavior. Can we change it to

"... and to make people of all backgrounds and groups feel welcome we have a code of conduct"

**Comment by tef** [comment]
I should have said 'good people from all backgrounds'

**Comment by adacable** [comment]
I still think that a code of conduct shouldn't be in our goals statement: It's a tool, not a goal. (not to say we shouldn't have one, but if we're outlining the problem, as we seem to be, then we shouldn't presuppose what parts of the answer will be.

**Comment by tef** [comment]
The reason i leave it in is that most tech groups do not have one.

**Comment by tef** [comment]
I've updated the README with some changes for style and tone in writing, and i've tried to capture some of the issues raised here too. Review welcome!

**Comment by public** [comment]
I agree with leaving it in the description. Your edit looks good to me.

**Comment by public** [comment]
> avoiding using the term "safe space", which is a rather overloaded term with many conflicting interpretations

I find this problematic though. This quality is unrelated to the other two and we've already have questions from people in IRC about safe space issues. I'm not sure we really have a satisfactory response to how we are going to deal with problems yet but maybe I've missed some patches.

**Comment by adacable** [comment]
@public While I would prefer safe space, I don't think we're in a place to provide it at the moment. I think in a few meetings we may be, but if we say we're a safe space and aren't then it's worse than not saying we will be until we can be sure we are.

**Comment by DRMacIver** [comment]
:+1: to @drcable's comment. Despite the ludicrous amount of effort we've put in relative to the number of meetups we've had we're not really in a position to have any real idea what our meetups look like. Lets not over-promise until we do.

**Comment by tef** [comment]
In another commit, which i forgot to mention this issue, I added 

"Although education and outreach are both important to us, the primary goal is to create a social group for people in and around tech, from all backgrounds, where they feel comfortable and welcome."

after some chat on irc, and discussion on the updates to the README

**Comment by public** [comment]
@drcable @DRMacIver I am not suggesting that we should claim we are capable of something we aren't but currently we don't have any consensus on what sort of safe space we are trying to create to even fail at being.

**Comment by tef** [comment]
I'm was to consider this issue closed as we've updated the page and README to make our intentions clear.

I've also removed the term safe space from the new groups advice and put in a note indicating that peoples safety is  a top priority. I don't know what our priorities are, so i've cushioned it for now.

**Comment by tef** [comment]
I'm going to close this issue for now.

**Comment by adacable** [comment]
:+1:
