### ISSUE TITLE
Page moves when "white on black version" is clicked

### ISSUE THREAD

**Issue by marksutherland** [computeranonymous/computer#99]
Steps to reproduce:

1) Visit index.html (http://computer.twentygototen.org/)
2) Click on "White on black version" in top right corner
3) Observe page jumps up by about a line, and you can now scroll up to the top, where previously the page was scrolled to the top.

Observed in FF 23.0.1 on OSX 10.8.4

**Comment by omgmog** [comment]
It looks like it's just jumping to the anchor point, this could be fixed by putting the "accessibility" ID on the `html` element instead of the `body` element.

**Comment by omgmog** [comment]
Should be fixed in #103

**Comment by marksutherland** [comment]
Yup, seems to work now.

I've noticed that if you go directly to http://computer.twentygototen.org/#accessibility then the button stops working, but that's unlikely to happen in normal usage.
